### ISSUE TITLE
Navbar della dashboard

### ISSUE THREAD

**Issue by gaga809** [FedericoZorgnotto/Vallauri-Orientati-Frontend#12]
C'è bisogno di fare la grafica della navbar che sarà presente nella dashboard dell'admin.
Lo stile è a discrezione di chi la crea, ma consiglierei di prendere come spunto la navbar del @Brick178  visibile [qui](https://www.figma.com/design/AyF6WOUFIqBw6DYGvtTkea/Untitled?node-id=0-1&node-type=canvas).

Sarebbe da implementare anche la logica, ma quella è una cosa che si può pensare anche dopo.

**Comment by FedericoZorgnotto** [comment]
È già presente una grafica da realizzare?
