### ISSUE TITLE
Gestione Token Login

### ISSUE THREAD

**Issue by gaga809** [FedericoZorgnotto/Vallauri-Orientati-Frontend#6]
C'è bisogno di gestire la logica dei Token di autenticazione del sito. Ogni login comprende due tipi di token, il token di accesso e il token di refresh.

### TOKEN DI ACCESSO 
Richiesto per qualsiasi operazione sul server. E' richiesto aggiungerlo all'header di ogni richiesta eccetto, naturalmente, quella di login.
Il Token ha una durata di 30 minuti massimi, quindi c'è bisogno di richiederlo di nuovo una volta scaduto. Per farlo, bisogna fare una richiesta a `/token/refresh`, passando il refresh token come parametro. (Leggere i docs per i dettagli)

### TOKEN DI REFRESH 
Viene dato insieme al primo accesso e al token di accesso. Durata massima di 30 giorni, poi c'è l'obbligo di rifare l'accesso. 

# COSA E' RICHIESTO
Implementazione della logica di salvataggio dei token in localstorage e autenticazione automatica col token in caso di accesso  già validato. Per farlo, modificare la libreria `loginModule.js` presente in `js/librerie/` nella main dir del progetto. L'autenticazione deve essere effettuata obbligatoriamente in ogni pagina, redirect in caso non sia possibile, fatta eccezzione per la pagina `login.html` e `index.html`.

**TUTTI I COMMIT DEVONO ESSERE ESEGUITI NEL RAMO DEVELOP**

NB: Le docs sono aggiornate in automatico tramite la libreria FastAPI, il quale è anche la libreria che si occupa di rispondere alle richieste.

**Comment by lucaed3001** [comment]
terminata
