### ISSUE TITLE
Creazione di una pagina di errore

### ISSUE THREAD

**Issue by lucaed3001** [FedericoZorgnotto/Vallauri-Orientati-Frontend#7]
E' necessaria la creazione della grafica di una pagina di errore, con messaggio di errore pesonalizzabile

stile e grafica a discrezione di chi se ne occupa

**Comment by FedericoZorgnotto** [comment]
mi sembra un buon accoppiamento questo, ve lo assegno anche sul progetto

**Comment by gaga809** [comment]
Ci ha pensato il gaga col support del pedro
